const rackets = [
  // adidas Padel 2026: model names verified in the official All For Padel catalogue. Performance values are comparator estimates, not manufacturer ratings.
  {id:'adidas-metalbone-2026',brand:'Adidas',name:'Metalbone 2026 – Ale Galán',shape:'Diamond',balance:'High',weight:360,power:92,control:78,spin:88,feel:'Hard'},
  {id:'adidas-metalbone-hrd-2026',brand:'Adidas',name:'Metalbone HRD+ 2026 – Ale Galán',shape:'Diamond',balance:'High',weight:365,power:95,control:71,spin:89,feel:'Hard'},
  {id:'adidas-metalbone-ctrl-2026',brand:'Adidas',name:'Metalbone CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:80,control:92,spin:87,feel:'Hard'},
  {id:'adidas-metalbone-carbon-ctrl-2026',brand:'Adidas',name:'Metalbone Carbon CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:80,control:88,spin:85,feel:'Medium'},
  {id:'adidas-metalbone-team-2026',brand:'Adidas',name:'Metalbone Team 2026',shape:'Diamond',balance:'Medium',weight:360,power:84,control:80,spin:82,feel:'Soft'},
  {id:'adidas-metalbone-team-light-2026',brand:'Adidas',name:'Metalbone Team Light 2026',shape:'Diamond',balance:'Medium',weight:350,power:79,control:84,spin:81,feel:'Soft'},
  {id:'adidas-metalbone-superlight-2026',brand:'Adidas',name:'Metalbone Superlight 2026',shape:'Round',balance:'Low',weight:345,power:72,control:89,spin:79,feel:'Soft'},
  {id:'adidas-arrow-hit-2026',brand:'Adidas',name:'Arrow Hit 2026',shape:'Diamond',balance:'High',weight:360,power:91,control:77,spin:86,feel:'Medium'},
  {id:'adidas-arrow-hit-ctrl-2026',brand:'Adidas',name:'Arrow Hit CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:79,control:90,spin:85,feel:'Medium'},
  {id:'adidas-arrow-hit-hexagon-2026',brand:'Adidas',name:'Arrow Hit Hexagon Cup 2026',shape:'Diamond',balance:'High',weight:360,power:87,control:78,spin:84,feel:'Medium'},
  {id:'adidas-arrow-hit-carbon-2026',brand:'Adidas',name:'Arrow Hit Carbon 2026',shape:'Diamond',balance:'Medium',weight:360,power:86,control:80,spin:84,feel:'Medium'},
  {id:'adidas-arrow-hit-carbon-ctrl-2026',brand:'Adidas',name:'Arrow Hit Carbon CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:79,control:88,spin:84,feel:'Medium'},
  {id:'adidas-arrow-hit-junior-blue-2026',brand:'Adidas',name:'Arrow Hit Junior Blue 2026',shape:'Round',balance:'Low',weight:325,power:63,control:90,spin:71,feel:'Soft'},
  {id:'adidas-arrow-hit-junior-pink-2026',brand:'Adidas',name:'Arrow Hit Junior Pink 2026',shape:'Round',balance:'Low',weight:325,power:63,control:90,spin:71,feel:'Soft'},
  {id:'adidas-cross-it-ctrl-2026',brand:'Adidas',name:'Cross IT CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:82,control:91,spin:87,feel:'Hard'},
  {id:'adidas-cross-it-light-2026',brand:'Adidas',name:'Cross IT Light 2026 – Martita Ortega',shape:'Round',balance:'Medium',weight:350,power:81,control:89,spin:87,feel:'Medium'},
  {id:'adidas-cross-it-carbon-2026',brand:'Adidas',name:'Cross IT Carbon 2026 – Maxi Arce',shape:'Diamond Oversize',balance:'High',weight:360,power:89,control:80,spin:86,feel:'Medium'},
  {id:'adidas-cross-it-carbon-ctrl-2026',brand:'Adidas',name:'Cross IT Carbon CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:80,control:89,spin:86,feel:'Medium'},
  {id:'adidas-cross-it-team-ctrl-2026',brand:'Adidas',name:'Cross IT Team CTRL 2026',shape:'Round',balance:'Medium',weight:360,power:77,control:87,spin:82,feel:'Soft'},
  {id:'adidas-cross-it-team-light-2026',brand:'Adidas',name:'Cross IT Team Light 2026',shape:'Diamond Oversize',balance:'Medium',weight:350,power:81,control:82,spin:81,feel:'Soft'},
  {id:'adidas-rx-series-2026',brand:'Adidas',name:'RX Series 2026',shape:'Round',balance:'Low',weight:360,power:72,control:89,spin:78,feel:'Soft'},
  {id:'adidas-rx-series-light-2026',brand:'Adidas',name:'RX Series Light 2026',shape:'Round',balance:'Low',weight:350,power:69,control:91,spin:77,feel:'Soft'},
  {id:'adidas-drive-blue-2026',brand:'Adidas',name:'Drive Blue 2026',shape:'Round',balance:'Low',weight:360,power:66,control:90,spin:73,feel:'Soft'},
  {id:'adidas-drive-black-2026',brand:'Adidas',name:'Drive Black 2026',shape:'Round',balance:'Low',weight:360,power:66,control:90,spin:73,feel:'Soft'},
  {id:'adidas-drive-light-2026',brand:'Adidas',name:'Drive Light 2026',shape:'Allround',balance:'Low',weight:345,power:67,control:88,spin:74,feel:'Soft'},
  {id:'adidas-match-black-2026',brand:'Adidas',name:'Match Black 2026',shape:'Allround',balance:'Low',weight:360,power:68,control:86,spin:74,feel:'Soft'},
  {id:'adidas-match-black-lime-2026',brand:'Adidas',name:'Match Black Lime 2026',shape:'Allround',balance:'Low',weight:360,power:68,control:86,spin:74,feel:'Soft'},
  {id:'adidas-match-light-2026',brand:'Adidas',name:'Match Light 2026',shape:'Allround',balance:'Low',weight:345,power:66,control:88,spin:73,feel:'Soft'},
  // Babolat Padel 2026: commercial model names and physical specifications verified in Babolat's official adult-racquet catalogue. Performance values are comparator estimates, not manufacturer ratings or FIP approval claims.
  {id:'babolat-air-origin-2026',brand:'Babolat',name:'Air Origin 2026',shape:'Teardrop',balance:'Medium',weight:345,power:72,control:88,spin:76,feel:'Soft'},
  {id:'babolat-air-veron-26-2026',brand:'Babolat',name:'Air Veron 2.6',shape:'Teardrop',balance:'Medium',weight:355,power:82,control:85,spin:83,feel:'Medium'},
  {id:'babolat-air-vertuo-26-2026',brand:'Babolat',name:'Air Vertuo 2.6',shape:'Teardrop',balance:'Medium',weight:345,power:75,control:88,spin:78,feel:'Soft'},
  {id:'babolat-air-viper-26-2026',brand:'Babolat',name:'Air Viper 2.6',shape:'Teardrop',balance:'Medium',weight:355,power:88,control:81,spin:88,feel:'Hard'},
  {id:'babolat-counter-origin-2026',brand:'Babolat',name:'Counter Origin 2026',shape:'Round',balance:'Medium',weight:355,power:71,control:90,spin:75,feel:'Soft'},
  {id:'babolat-counter-veron-26-2026',brand:'Babolat',name:'Counter Veron 2.6',shape:'Round',balance:'High',weight:365,power:80,control:90,spin:83,feel:'Medium'},
  {id:'babolat-counter-vertuo-26-2026',brand:'Babolat',name:'Counter Vertuo 2.6',shape:'Round',balance:'Medium',weight:350,power:74,control:91,spin:77,feel:'Soft'},
  {id:'babolat-counter-viper-26-2026',brand:'Babolat',name:'Counter Viper 2.6',shape:'Round',balance:'High',weight:365,power:86,control:90,spin:86,feel:'Hard'},
  {id:'babolat-technical-origin-plus-2026',brand:'Babolat',name:'Technical Origin + 2026',shape:'Diamond',balance:'Medium',weight:355,power:77,control:83,spin:78,feel:'Soft'},
  {id:'babolat-technical-veron-30-2026',brand:'Babolat',name:'Technical Veron 3.0',shape:'Diamond',balance:'High',weight:360,power:87,control:81,spin:84,feel:'Medium'},
  {id:'babolat-technical-viper-30-2026',brand:'Babolat',name:'Technical Viper 3.0',shape:'Diamond',balance:'High',weight:370,power:95,control:72,spin:90,feel:'Hard'},
  {id:'babolat-technical-viper-soft-30-2026',brand:'Babolat',name:'Technical Viper Soft 3.0',shape:'Diamond',balance:'High',weight:365,power:91,control:77,spin:88,feel:'Medium'},
  {id:'babolat-veron-juan-lebron-30-2026',brand:'Babolat',name:'Veron Juan Lebrón 3.0',shape:'Diamond',balance:'High',weight:360,power:87,control:81,spin:86,feel:'Medium'},
  {id:'babolat-viper-juan-lebron-30-2026',brand:'Babolat',name:'Viper Juan Lebrón 3.0',shape:'Diamond',balance:'High',weight:370,power:95,control:72,spin:91,feel:'Hard'},
  {id:'babolat-viper-juan-lebron-fw-30-2026',brand:'Babolat',name:'Viper Juan Lebrón 3.0 FW',shape:'Diamond',balance:'High',weight:370,power:95,control:72,spin:91,feel:'Hard'},
  {id:'babolat-viper-soft-juan-lebron-30-2026',brand:'Babolat',name:'Viper Soft Juan Lebrón 3.0',shape:'Diamond',balance:'High',weight:365,power:91,control:77,spin:89,feel:'Medium'},
  // Bullpadel Padel 2026: 24 current commercial models cross-checked against Bullpadel's official product pages and official 2026 collection retailer. Manufacturer shape, balance and weight inform this catalogue; power/control/spin/feel remain comparator estimates.
  {id:'bullpadel-hack-04-2026',brand:'Bullpadel',name:'Hack 04 2026 – Paquito Navarro',shape:'Diamond',balance:'High',weight:370,power:93,control:78,spin:88,feel:'Hard'},
  {id:'bullpadel-hack-04-hybrid-2026',brand:'Bullpadel',name:'Hack 04 Hybrid 2026 – Paquito Navarro',shape:'Hybrid',balance:'Low',weight:370,power:80,control:91,spin:87,feel:'Medium'},
  {id:'bullpadel-hack-04-comfort-2026',brand:'Bullpadel',name:'Hack 04 Comfort 2026',shape:'Diamond',balance:'High',weight:365,power:87,control:80,spin:85,feel:'Medium'},
  {id:'bullpadel-hack-04-hybrid-cloud-2026',brand:'Bullpadel',name:'Hack 04 Hybrid Cloud 2026',shape:'Hybrid',balance:'Low',weight:365,power:76,control:90,spin:82,feel:'Soft'},
  {id:'bullpadel-vertex-05-2026',brand:'Bullpadel',name:'Vertex 05 2026 – Juan Tello',shape:'Diamond',balance:'High',weight:370,power:88,control:85,spin:88,feel:'Medium'},
  {id:'bullpadel-vertex-05-hybrid-2026',brand:'Bullpadel',name:'Vertex 05 Hybrid 2026',shape:'Hybrid',balance:'Low',weight:370,power:80,control:90,spin:87,feel:'Medium'},
  {id:'bullpadel-vertex-05-comfort-2026',brand:'Bullpadel',name:'Vertex 05 Comfort 2026',shape:'Diamond',balance:'High',weight:365,power:82,control:85,spin:84,feel:'Soft'},
  {id:'bullpadel-vertex-05-geo-2026',brand:'Bullpadel',name:'Vertex 05 GEO 2026 – Pablo Cardona',shape:'Geometric',balance:'High',weight:370,power:91,control:80,spin:87,feel:'Hard'},
  {id:'bullpadel-vertex-05-woman-2026',brand:'Bullpadel',name:'Vertex 05 Woman 2026 – Delfi Brea',shape:'Diamond',balance:'Medium',weight:355,power:78,control:85,spin:85,feel:'Soft'},
  {id:'bullpadel-vertex-05-woman-cloud-2026',brand:'Bullpadel',name:'Vertex 05 Woman Cloud 2026',shape:'Diamond',balance:'Medium',weight:355,power:74,control:88,spin:81,feel:'Soft'},
  {id:'bullpadel-vertex-advance-2026',brand:'Bullpadel',name:'Vertex Advance 2026',shape:'Diamond',balance:'Medium',weight:360,power:78,control:83,spin:80,feel:'Medium'},
  {id:'bullpadel-neuron-02-2026',brand:'Bullpadel',name:'Neuron 02 2026 – Fede Chingotto',shape:'Hybrid',balance:'Low',weight:370,power:80,control:94,spin:86,feel:'Hard'},
  {id:'bullpadel-neuron-02-edge-2026',brand:'Bullpadel',name:'Neuron 02 Edge 2026 – Fede Chingotto',shape:'Geometric',balance:'Medium',weight:370,power:87,control:91,spin:86,feel:'Hard'},
  {id:'bullpadel-neuron-02-cloud-2026',brand:'Bullpadel',name:'Neuron 02 Cloud 2026',shape:'Hybrid',balance:'Medium',weight:370,power:74,control:89,spin:80,feel:'Soft'},
  {id:'bullpadel-xplo-2026',brand:'Bullpadel',name:'XPLO 2026 – Martín Di Nenno',shape:'Geometric',balance:'High',weight:370,power:96,control:74,spin:87,feel:'Hard'},
  {id:'bullpadel-xplo-comfort-2026',brand:'Bullpadel',name:'XPLO Comfort 2026 – Martín Di Nenno',shape:'Geometric',balance:'High',weight:365,power:89,control:78,spin:84,feel:'Medium'},
  {id:'bullpadel-icon-2026',brand:'Bullpadel',name:'Icon 2026 – Juan Martín Díaz',shape:'Diamond',balance:'High',weight:373,power:87,control:82,spin:86,feel:'Medium'},
  {id:'bullpadel-elite-woman-2026',brand:'Bullpadel',name:'Elite Woman 2026 – Gemma Triay',shape:'Teardrop',balance:'Medium',weight:355,power:82,control:86,spin:85,feel:'Medium'},
  {id:'bullpadel-flow-legend-2026',brand:'Bullpadel',name:'Flow Legend 2026 – Alejandra Salazar',shape:'Diamond',balance:'Medium',weight:350,power:81,control:84,spin:84,feel:'Medium'},
  {id:'bullpadel-ionic-light-2026',brand:'Bullpadel',name:'Ionic Light 2026',shape:'Hybrid',balance:'Medium',weight:350,power:75,control:86,spin:80,feel:'Soft'},
  {id:'bullpadel-indiga-boy-junior-2026',brand:'Bullpadel',name:'Indiga Boy Junior 2026',shape:'Diamond',balance:'Medium',weight:335,power:68,control:81,spin:72,feel:'Soft'},
  {id:'bullpadel-hack-junior-2026',brand:'Bullpadel',name:'Hack Junior 2026',shape:'Diamond',balance:'Medium',weight:335,power:71,control:80,spin:75,feel:'Medium'},
  {id:'bullpadel-vertex-junior-boy-2026',brand:'Bullpadel',name:'Vertex Junior Boy 2026',shape:'Diamond',balance:'Medium',weight:335,power:73,control:80,spin:76,feel:'Medium'},
  {id:'bullpadel-vertex-junior-girl-2026',brand:'Bullpadel',name:'Vertex Junior Girl 2026',shape:'Diamond',balance:'Medium',weight:335,power:71,control:82,spin:76,feel:'Medium'},
  // HEAD Padel 2026: 11 current seasonal models verified on HEAD's official shop and product pages. Shape, balance and weight are manufacturer specifications; power/control/spin/feel remain comparator estimates. FIP does not publish a public per-racket approval list, so none is labelled "FIP approved".
  {id:'head-coello-pro-2026',brand:'Head',name:'Coello Pro 2026 – Arturo Coello',shape:'Diamond',balance:'High',weight:370,power:95,control:73,spin:90,feel:'Hard'},
  {id:'head-coello-motion-2026',brand:'Head',name:'Coello Motion 2026 – Arturo Coello',shape:'Diamond',balance:'High',weight:360,power:90,control:79,spin:89,feel:'Hard'},
  {id:'head-coello-team-2026',brand:'Head',name:'Coello Team 2026 – Arturo Coello',shape:'Diamond',balance:'High',weight:360,power:83,control:84,spin:80,feel:'Soft'},
  {id:'head-coello-vibe-2026',brand:'Head',name:'Coello Vibe 2026 – Arturo Coello',shape:'Teardrop',balance:'Medium',weight:356,power:76,control:87,spin:75,feel:'Soft'},
  {id:'head-coello-junior-2026',brand:'Head',name:'Coello Junior 2026 – Arturo Coello',shape:'Teardrop',balance:'Medium',weight:310,power:62,control:90,spin:70,feel:'Soft'},
  {id:'head-radical-pro-2026',brand:'Head',name:'Radical Pro 2026',shape:'Teardrop',balance:'Medium',weight:370,power:82,control:93,spin:83,feel:'Hard'},
  {id:'head-radical-motion-2026',brand:'Head',name:'Radical Motion 2026',shape:'Teardrop',balance:'Medium',weight:355,power:79,control:94,spin:83,feel:'Hard'},
  {id:'head-radical-team-2026',brand:'Head',name:'Radical Team 2026',shape:'Teardrop',balance:'Low',weight:360,power:75,control:91,spin:79,feel:'Soft'},
  {id:'head-radical-team-light-2026',brand:'Head',name:'Radical Team Light 2026',shape:'Round',balance:'Low',weight:339,power:68,control:91,spin:74,feel:'Soft'},
  {id:'head-bolt-2026',brand:'Head',name:'Bolt 2026',shape:'Teardrop',balance:'Medium',weight:352,power:74,control:86,spin:75,feel:'Soft'},
  {id:'head-vibe-2026',brand:'Head',name:'Vibe 2026',shape:'Teardrop',balance:'Medium',weight:350,power:72,control:88,spin:74,feel:'Soft'},
  // KUIKMA Padel catalogue, verified 25 Aug 2026 against Decathlon's current KUIKMA range and product pages. These are distinct currently sold product types, not colourways, packs or second-life listings. Manufacturer shape, balance and weight inform this catalogue; power/control/spin/feel remain comparator estimates. FIP publishes no public per-racket approval list, so none is labelled "FIP approved".
  {id:'kuikma-pr-open-2026',brand:'Kuikma',name:'PR Open',shape:'Round',balance:'Low',weight:320,power:62,control:94,spin:66,feel:'Soft'},
  {id:'kuikma-control-pro-2026',brand:'Kuikma',name:'Control Pro – Álvaro Meléndez',shape:'Round',balance:'Medium',weight:370,power:78,control:95,spin:89,feel:'Medium'},
  {id:'kuikma-pr-comfort-2026',brand:'Kuikma',name:'PR Comfort',shape:'Round',balance:'Low',weight:350,power:70,control:91,spin:73,feel:'Medium'},
  {id:'kuikma-pr-comfort-soft-2026',brand:'Kuikma',name:'PR Comfort Soft',shape:'Round',balance:'Low',weight:350,power:66,control:93,spin:70,feel:'Soft'},
  {id:'kuikma-hybrid-pro-2026',brand:'Kuikma',name:'Hybrid Pro – Coki Nieto / Lucía Sainz',shape:'Teardrop',balance:'Medium',weight:365,power:88,control:86,spin:88,feel:'Hard'},
  {id:'kuikma-control-metal-2026',brand:'Kuikma',name:'Control Metal',shape:'Round',balance:'Low',weight:365,power:75,control:92,spin:84,feel:'Soft'},
  {id:'kuikma-pr-hybrid-carbon-dynamic-2026',brand:'Kuikma',name:'PR Hybrid Carbon Dynamic',shape:'Teardrop',balance:'Medium',weight:355,power:84,control:88,spin:87,feel:'Hard'},
  {id:'kuikma-pr-react-2026',brand:'Kuikma',name:'PR React',shape:'Teardrop',balance:'Medium',weight:360,power:78,control:84,spin:77,feel:'Medium'},
  {id:'kuikma-power-pro-2026',brand:'Kuikma',name:'Power Pro',shape:'Diamond',balance:'Low',weight:375,power:93,control:78,spin:89,feel:'Hard'},
  {id:'kuikma-pr-hybrid-carbon-coki-nieto-2026',brand:'Kuikma',name:'PR Hybrid Carbon – Coki Nieto',shape:'Teardrop',balance:'Medium',weight:370,power:86,control:86,spin:86,feel:'Medium'},
  {id:'kuikma-pr-boost-hybrid-2026',brand:'Kuikma',name:'PR Boost Hybrid',shape:'Diamond',balance:'Medium',weight:355,power:83,control:82,spin:78,feel:'Soft'},
  {id:'kuikma-pr-control-carbon-dynamic-2026',brand:'Kuikma',name:'PR Control Carbon Dynamic',shape:'Round',balance:'Medium',weight:355,power:80,control:91,spin:86,feel:'Hard'},
  {id:'kuikma-pr-power-carbon-dynamic-2026',brand:'Kuikma',name:'PR Power Carbon Dynamic',shape:'Diamond',balance:'High',weight:355,power:89,control:80,spin:86,feel:'Hard'},
  {id:'kuikma-pr-fun-2026',brand:'Kuikma',name:'PR Fun (5–8 years)',shape:'Round',balance:'Low',weight:270,power:55,control:92,spin:63,feel:'Soft'},
  {id:'kuikma-power-metal-2026',brand:'Kuikma',name:'Power Metal',shape:'Diamond',balance:'High',weight:365,power:87,control:78,spin:85,feel:'Soft'},
  {id:'kuikma-pr-react-soft-2026',brand:'Kuikma',name:'PR React Soft',shape:'Teardrop',balance:'Medium',weight:342,power:70,control:90,spin:77,feel:'Soft'},
  {id:'kuikma-pr-game-2026',brand:'Kuikma',name:'PR Game (children)',shape:'Round',balance:'Low',weight:310,power:61,control:92,spin:66,feel:'Soft'},
  {id:'kuikma-pr-evolution-2026',brand:'Kuikma',name:'PR Evolution (9–12 years)',shape:'Round',balance:'Low',weight:330,power:64,control:91,spin:68,feel:'Medium'},
  {id:'kuikma-control-carbon-2026',brand:'Kuikma',name:'Control Carbon',shape:'Round',balance:'Low',weight:370,power:79,control:94,spin:87,feel:'Medium'},
  {id:'kuikma-pr-rental-2026',brand:'Kuikma',name:'PR Rental',shape:'Round',balance:'Low',weight:350,power:68,control:90,spin:70,feel:'Soft'},
  {id:'kuikma-pr-120-light-2026',brand:'Kuikma',name:'PR 120 Light (9–11 years)',shape:'Teardrop',balance:'High',weight:330,power:63,control:82,spin:65,feel:'Soft'},
  {id:'kuikma-power-carbon-2026',brand:'Kuikma',name:'Power Carbon',shape:'Diamond',balance:'High',weight:372,power:91,control:78,spin:88,feel:'Medium'},
  {id:'kuikma-pr-power-light-2026',brand:'Kuikma',name:'PR Power Light',shape:'Diamond',balance:'Medium',weight:355,power:80,control:81,spin:78,feel:'Medium'},
  {id:'kuikma-power-boost-2026',brand:'Kuikma',name:'Power Boost',shape:'Diamond',balance:'High',weight:360,power:85,control:80,spin:80,feel:'Soft'},
  {id:'kuikma-hybrid-metal-2026',brand:'Kuikma',name:'Hybrid Metal',shape:'Teardrop',balance:'Low',weight:365,power:76,control:90,spin:83,feel:'Soft'},
  {id:'nox-at10-12k',brand:'Nox',name:'AT10 Genius 12K',shape:'Teardrop',balance:'Medium',weight:360,power:85,control:86,spin:88,feel:'Medium'},
  {id:'nox-ml10',brand:'Nox',name:'ML10 Pro Cup',shape:'Round',balance:'Low',weight:360,power:75,control:91,spin:84,feel:'Soft'},
  {id:'oxdog-hyper-pro',brand:'Oxdog',name:'Hyper Pro 2.0',shape:'Diamond',balance:'High',weight:365,power:92,control:74,spin:85,feel:'Hard'},
  {id:'siux-electra',brand:'Siux',name:'Electra ST5 Pro',shape:'Hybrid',balance:'Medium',weight:360,power:86,control:82,spin:88,feel:'Medium'},
  {id:'wilson-bela-pro',brand:'Wilson',name:'Bela Pro V3',shape:'Diamond',balance:'High',weight:370,power:92,control:73,spin:87,feel:'Hard'},
  {id:'wilson-blade-pro',brand:'Wilson',name:'Blade Pro V3',shape:'Teardrop',balance:'Medium',weight:365,power:86,control:83,spin:86,feel:'Medium'}
];
const $=id=>document.getElementById(id); const brands=[...new Set(rackets.map(r=>r.brand))].sort();
function option(value,text){const el=document.createElement('option');el.value=value;el.textContent=text;return el}
function populateBrand(side){const select=$(`${side}-racket-brand`);select.replaceChildren();brands.forEach(b=>select.add(option(b,b)));select.add(option('other','OTHER / NOT LISTED'));select.value=side==='current'?'Nox':'Head';populateModels(side)}
function populateModels(side){const brand=$(`${side}-racket-brand`).value,model=$(`${side}-racket`),custom=$(`${side}-other`);custom.classList.toggle('hidden',brand!=='other');model.disabled=brand==='other';model.replaceChildren();if(brand==='other'){model.add(option('other','Enter your model below'));return}rackets.filter(r=>r.brand===brand).forEach(r=>model.add(option(r.id,r.name)));}
function getRacket(side){const brand=$(`${side}-racket-brand`).value;if(brand==='other'){return {brand:$(`${side}-other-brand`).value.trim()||'Unlisted',name:$(`${side}-other-model`).value.trim()||'padel racket',year:Number($(`${side}-other-year`).value)||2026,shape:'Unknown',balance:'Unknown',weight:360,power:78,control:78,spin:78,feel:'Unknown',custom:true}}return {...rackets.find(r=>r.id===$(`${side}-racket`).value),year:2026}}
function drawStats(side){const r=getRacket(side);$(`${side}-stats`).innerHTML=`<span class="mini-stat">POWER<b>${r.power}</b></span><span class="mini-stat">CONTROL<b>${r.control}</b></span><span class="mini-stat">SPIN<b>${r.spin}</b></span><span class="mini-stat">${r.weight}G<b>${r.shape}</b></span><span class="mini-stat">YEAR<b>${r.year}</b></span>`}
function render(){drawStats('current');drawStats('target')}
function recommendation(current,target){const priority=$('priority').value,side=$('side').value,comfort=$('comfort').value;const delta={power:target.power-current.power,control:target.control-current.control,spin:target.spin-current.spin};let score=target.control*0.44+target.power*0.31+target.spin*.25;if(priority==='power')score=target.power*.49+target.control*.26+target.spin*.25;if(priority==='balance')score=target.power*.36+target.control*.36+target.spin*.28;if(comfort==='important'&&target.feel==='Hard')score-=8;if(side==='right'&&target.control>=84)score+=4;if(side==='left'&&target.power>=88)score+=4;const direction=n=>n>0?`+${n}`:String(n);const advice=score>=84?'A strong fit for the priorities you selected.':score>=78?'A plausible change, with a clear trade-off to test first.':'Choose only after a court test; the profile and pala character are not a natural match.';return {delta,score:Math.round(score),advice,direction}}
function compare(){const current=getRacket('current'),target=getRacket('target'),r=recommendation(current,target),diff=(metric,label)=>`<div class="metric"><b>${label}</b><span><i style="width:${current[metric]}%"></i><em style="width:${target[metric]}%"></em></span><strong>${current[metric]} → ${target[metric]} <small>${r.direction(r.delta[metric])}</small></strong></div>`;$('results').classList.remove('hidden');$('results').innerHTML=`<div class="result-intro"><p class="eyebrow">03 / COMPARISON</p><h2>${current.brand} ${current.name}<br />vs ${target.brand} ${target.name}</h2><p>${r.advice}</p></div><div class="comparison-details"><div class="metrics">${diff('power','POWER')}${diff('control','CONTROL')}${diff('spin','SPIN')}</div><aside class="compatibility-card"><b>${r.score}/100</b><div><h3>Profile fit</h3><p>${target.shape} shape · ${target.balance.toLowerCase()} balance · ${target.weight} g · ${target.feel.toLowerCase()} feel · ${target.year} model year.</p></div></aside></div><div class="padel-verdict"><h3>What will change on court</h3><p><b>${target.brand} ${target.name}</b> is a ${target.shape.toLowerCase()} pala with ${target.balance.toLowerCase()} balance. ${r.delta.power>5?'Expect more help on viboras, bandejas and finishing overheads.':r.delta.power<-5?'You give up some finishing power for easier placement.':'Its finishing power stays close to your current pala.'} ${r.delta.control>5?'The larger control margin should help on returns, volleys and defensive lobs.':r.delta.control<-5?'It will ask for cleaner timing on returns and defensive lobs.':'The control level remains broadly familiar.'} Try it with your usual ball and overgrip before buying.</p></div>`;$('results').scrollIntoView({behavior:'smooth',block:'start'})}
['current','target'].forEach(side=>{populateBrand(side);$(`${side}-racket-brand`).addEventListener('change',()=>{populateModels(side);render()});$(`${side}-racket`).addEventListener('change',render);$(`${side}-other-brand`).addEventListener('input',render);$(`${side}-other-model`).addEventListener('input',render);$(`${side}-other-year`).addEventListener('input',render)});render();$('compare-button').addEventListener('click',compare);
